[project]
name = "python"
version = "0.1.0"
description = ""
authors = [
    { name = "Eduardo Cejudo", email = "eduardo_cejudo@outlook.com" }
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.poetry]
packages = [{ include = "python", from = "src" }]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "black (>=26.5.1,<27.0.0)",
    "ruff (>=0.16.1,<0.17.0)",
    "pytest (>=9.1.1,<10.0.0)",
    "pre-commit (>=4.6.1,<5.0.0)"
]

# ----------------------------
# Black
# ----------------------------
[tool.black]
line-length = 88
target-version = ["py312"]

# ----------------------------
# Ruff
# ----------------------------
[tool.ruff]
line-length = 88
target-version = "py312"

[tool.ruff.lint]
select = [
    "E", # pycodestyle
    "F", # Pyflakes
    "I", # Ordenar imports (reemplaza isort)
    "B",
    "UP"
]

# Opcional: reglas que puedes ignorar
ignore = []

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

# ----------------------------
# Pytest
# ----------------------------
[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]

[tool.isort]
profile = "black"

[tool.mypy]
python_version = "3.12"
strict = true