# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ordenes.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ordenes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rordenes.proto\x12\x0e\x63oches.ordenes\"D\n\x11\x43rearOrdenRequest\x12\x0f\n\x07\x63liente\x18\x01 \x01(\t\x12\x0e\n\x06modelo\x18\x02 \x01(\t\x12\x0e\n\x06precio\x18\x03 \x01(\x01\"L\n\rOrdenResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x63liente\x18\x02 \x01(\t\x12\x0e\n\x06modelo\x18\x03 \x01(\t\x12\x0e\n\x06precio\x18\x04 \x01(\x01\"0\n\x0cOrderCreated\x12\x10\n\x08orden_id\x18\x01 \x01(\t\x12\x0e\n\x06modelo\x18\x02 \x01(\t2`\n\x0eOrdenesService\x12N\n\nCrearOrden\x12!.coches.ordenes.CrearOrdenRequest\x1a\x1d.coches.ordenes.OrdenResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ordenes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREARORDENREQUEST']._serialized_start=33
  _globals['_CREARORDENREQUEST']._serialized_end=101
  _globals['_ORDENRESPONSE']._serialized_start=103
  _globals['_ORDENRESPONSE']._serialized_end=179
  _globals['_ORDERCREATED']._serialized_start=181
  _globals['_ORDERCREATED']._serialized_end=229
  _globals['_ORDENESSERVICE']._serialized_start=231
  _globals['_ORDENESSERVICE']._serialized_end=327
# @@protoc_insertion_point(module_scope)
