name: Pruebas

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Instalar Poetry
        run: pipx install poetry
      - name: Instalar dependencias
        run: poetry install --with dev
      - name: Ejecutar pruebas y cobertura
        run: poetry run pytest --cov --cov-report=term-missing
